### ISSUE TITLE
TextField with a right aligned inline icon

### ISSUE THREAD

**Issue by dinumihnea** [appreciated/material#19]
Hi, Thanks for great design;
It would be a good style name for button with icon to the right.

**Comment by appreciated** [comment]
Since the material Theme is using the Valo theme engine you can actually use the predefined styles for that. Most of them are shown in the [Valo Theme Test](https://demo.vaadin.com/valo-theme/#!buttons-and-links).  
If you find the Valo stylenames not working in the Material theme you can reopen this issue.

**Comment by dinumihnea** [comment]
Sorry, I want to say TextField with Icon on Right

**Comment by appreciated** [comment]
Can you give an image example how you imagine the requested feature to be? I'm not sure if many users will need this feature. If not so you might need to implement it yourself. You are very welcome to create a pull request.

**Comment by dinumihnea** [comment]
Icon position like this:

![flat-design-07b](https://user-images.githubusercontent.com/20513656/28606917-23543840-71e2-11e7-9ed9-cd84e042a1d8.jpg)
![01](https://user-images.githubusercontent.com/20513656/28606926-29b10c7c-71e2-11e7-9b7f-d33915fe2ed2.jpg)

**Comment by appreciated** [comment]
Since this feature does not conform with valo neither with the material guidelines, I see no point in adding it. If you wish you may contribute it yourself.  

You could use a solution as follows, but it is only tested for TextField. There might be problems if you use this solution for other Fields like DateField, DateTimeField, ComboBox.

Java Example Code
````
TextField field = new TextField();
field.addStyleNames("inline-icon","textfield-inline-icon-right");
field.setIcon(VaadinIcons.EDIT);
````

(S)CSS:
````
.v-caption-textfield-inline-icon-right.v-caption-inline-icon  span.v-icon {
    right: 0;
    left: unset;
}
.inline-icon.textfield-inline-icon-right {
    padding-left: 0px;
    padding-right: 45px;
}
````

**Comment by dinumihnea** [comment]
Great! Thanks
