### ISSUE TITLE
Simple Button Hover Style

### ISSUE THREAD

**Issue by dinumihnea** [appreciated/material#24]
background color for colored buttons  (primary, danger, friendly...) on hover is too transparent
example: background: valo-font-color($v-friendly-color, **0.1**); 
may be looks good: background: valo-font-color($v-friendly-color, **0.7**);

**Comment by appreciated** [comment]
> example: background: valo-font-color($v-friendly-color, 0.1);
> may be looks good: background: valo-font-color($v-friendly-color, 0.7);

> [valo-font-color](https://vaadin.com/api/valo/#function-valo-font-color)($bg-color)
> Returns a font color with enough contrast for the given background color.

I think you mix up transparency with with contrast. 

But sure I'll investigate it. Since the ripple was added the hover it is actually not that important anymore.

In my opinion a value of 0.7 is far over the top (note all buttons are :hover)

![unbenannt](https://user-images.githubusercontent.com/1729845/29046767-2cf47fe0-7bc9-11e7-9671-f99c2affe8de.PNG)

**Comment by appreciated** [comment]
Checkout Version 1.0.3
