### ISSUE TITLE
Button hover cursor

### ISSUE THREAD

**Issue by dinumihnea** [appreciated/material#27]
Hello my friend.
This is not a problem, but is a proposal.
Material Design Guidelines does not provide the button **cursor** style, but I think this is unacceptable for web pages.
Here are some examples: 
https://drive.google.com
https://plus.google.com/discover

Think about whether to add, I think it will be a pretty good addition.

Thanks

**Comment by appreciated** [comment]
Hello Dinu! 
sorry to correct you slightly but in the case of the buttons, this is actually a bug 😁 [(if you take a look at the original Valo Buttons)](https://demo.vaadin.com/valo-theme/#!common) due to the fact that I removed the Valo Button styles completely. I seemed to have unknowingly dropped the `cursor: pointer;` feature. 

In case of other styles like "ripple" and "card-hoverable" styles this will be added 😉.

Thanks again for the finding!

**Comment by dinumihnea** [comment]
😁
& add please `cursor: not-allowed`  (or another)  for disabled buttons

**Comment by appreciated** [comment]
Hmm I cannot agree on the `cursor: not-allowed` for disabled buttons this seems to be a non standard behaviour (though I must admit that I haven't put much research into that)
For example [Vaadin (Valo)](https://demo.vaadin.com/valo-theme/#!buttons-and-links), [Angular](https://material.angularjs.org/latest/demo/button) and [Materialize](http://materializecss.com/buttons.html) don't do this. But for example [Bootstrap](https://www.w3schools.com/bootstrap/bootstrap_buttons.asp) does it. My argument is that since this theme derives from Valo and has much in common with the design of angular and materialize it does not really make sense to break the "rules" here 🤔. 

Though it is quite simple to add this by yourself:
````
.v-button.v-disabled {
    cursor: not-allowed
}
```` 

If you'd like you can introduce it via a variable which is by default "false", when set to true the desired behaviour will be enabled. 😉

**Comment by dinumihnea** [comment]
Ok, I agree with you.
