### ISSUE TITLE
Grid Rows Required alternate row colors as  valo theme does

### ISSUE THREAD

**Issue by jaysinghsoni** [appreciated/material#32]
Hi 
First many thanks to fix the issue no. 30 actually there were two points in which one is fixed but second point was to provide the grid rows alternate row coloring as valo theme does so if you could provide  some  details how this could be don or fix it it would be great once again thanks for the great efforts

**Comment by appreciated** [comment]
[To have an altering background color each row is not encouraged by the material design guidelines](https://material.io/guidelines/components/data-tables.html) Since this is a material theme I recommand leaving it as it is.

If that still does not hold you back try to add this to your custom theme:
````
$grid-uneven-color: #123456;
// Header row
.v-grid-header .v-grid-cell {
    background: $grid-uneven-color !important;
}
// Header context menu
.v-grid-sidebar.v-contextmenu {
    background: $grid-uneven-color !important;
}
// Rows
.v-grid-row-stripe > td {
    background-color: $grid-uneven-color !important;
}
````

If you want this as a feature you are welcome to create a pull request with the necessary changes.

**Comment by appreciated** [comment]
Any progress?
