### ISSUE TITLE
using Material Theme in Vok

### ISSUE THREAD

**Issue by NiranjanShah** [appreciated/material#43]
How to use your Material Theme in Vaadin on Kotlin / Vaadin flow

https://github.com/mvysny/vaadin-on-kotlin

**Comment by appreciated** [comment]
There is (and there won't be) Vaadin Flow support with this addon since too much was changed. 
I will have to start pretty much from the beginning (surely some stuff can be reused but I guess not too much). Also since I haven't worked yet with Vaadin Flow I cannot tell any details. 
But since I'm a great fan of the material theme. I might do a new addon which brings the same look and feel to Vaadin Flow. 
Note that a new Theme that was introduced in Vaadin Flow which seems to be influenced a lot by the Material Design. So no promises here.
