### ISSUE TITLE
Instead of set the style every time, could I set the default style for component?

### ISSUE THREAD

**Issue by yurili8** [appreciated/material#50]
For example, When I want to use the flat and custom style for the button, I have to set the style for the button every time. could I achieve this in the css file?

any help is appreciated.

**Comment by appreciated** [comment]
You can also use a Java class that extend `Button`. Add the css class in the constructor and reuse the Java class. At least this is what I would do.

**Comment by yurili8** [comment]
> You can also use a Java class that extend `Button`. Add the css class in the constructor and reuse the Java class. At least this is what I would do.

thanks for your quick reply.
because the Button is already in may places in my project, If I extend it , too much change will be made. I am wondering whether I could do this by writing some CSS code.

**Comment by appreciated** [comment]
About how "many" places where you use these kind of `Button` are we talking 50? 200? Changing this is in your Java Code is the much cleaner approach. Also you can estimate the time that this change takes much better since the amount of effort is very clear. Also when doing this you can later on change all the buttons at once to your liking. 
I can guarantee, there is no easy way to do this via css, What you can do is copying this project, and change the look of the default button, not clean and you still have to touch the Java code.

I am not able to give reliable advice since your description lacks of details.

**Comment by yurili8** [comment]
> About how "many" places where you use these kind of `Button` are we talking 50? 200? Changing this is in your Java Code is the much cleaner approach. Also you can estimate the time that this change takes much better since the amount of effort is very clear. Also when doing this you can later on change all the buttons at once to your liking.
> I can guarantee, there is no easy way to do this via css, What you can do is copying this project, and change the look of the default button, not clean and you still have to touch the Java code.
> 
> I am not able to give reliable advice since your description lacks of details.

thanks for your advice.
